### ISSUE TITLE
config and launch

### ISSUE THREAD

**Issue by philobbe** [SpaceXLaunchBot/SpaceXLaunchBot#14]
where config the bot and what command to start it please ?
There are no informations about that.
Thanks

**Comment by psidex** [comment]
Hi,

Currently there is no guide on how to run the bot yourself, and at this time I don't plan to create one.

If you want to see an example of how it's deployed take a look [here](https://github.com/SpaceXLaunchBot/deploy).

Unless you plan to fork this repo and implement your own features I suggest you just invite the instance I'm hosting ([link](https://discord.com/oauth2/authorize?client_id=411618411169447950&scope=bot&permissions=19456)), it's much easier and will provide the exact same features and experience as an instance that you host yourself :]

**Comment by philobbe** [comment]
Thanks for you response and explaination
I would prefer to host it myself and understand what is the problem...
It seems a file is missing:
no such file or directory, open /home/pi/spacexlaunchbot/package.json
package.json is missing a think

**Comment by psidex** [comment]
The reason why it says that is because this is not written in JavaScript, it is a discord.py bot written in Python.

If you really want to run it yourself you will need:

- Python 3
- All the packages in requirements.txt installed using `pip`
- A PostgreSQL server running where the bot can access it
- All of the variables in `spacexlaunchbot/config.py` filled out to your specific setup (including the environment variables)
- The bot installed using the setup.py file

If you don't understand any of those points I strongly suggest you just use the instance I'm hosting
