### ISSUE TITLE
can this be self hosted?

### ISSUE THREAD

**Issue by rich1488** [SpaceXLaunchBot/SpaceXLaunchBot#16]
and how would I go about doing it? i see theres a docker deploy repo, but i use a raspberry pi.

looks like everything thats needed is in the directories. whats the difference between spacexlaunchbot/ and spacexlaunchbot/spacexlaunchbot/ ?

**Comment by psidex** [comment]
Hi,

This is self-hostable but I think it will take a bit of work if you want to get it running on a pi.

> and how would I go about doing it? i see theres a docker deploy repo, but i use a raspberry pi.

Yeah, [deploy](https://github.com/SpaceXLaunchBot/deploy) contains all of the code required to set up and run the project on a linux server running Docker.

It is totally possible to get it running on a pi without Docker but you would have to figure out how to get things running correctly, such as postgres, and then you're going to have to tweak the config(s) and env vars to make things work.

If you take a look around the deploy repo you can see the deploy script and how it sets everything up for Docker deployment, you would basically want to mirror those steps but just with the non-docker conterparts (e.g. postgres running normally instead of in a container). There's also the config for running the site in there, but you can ignore that unless you want to host a clone of the website as well!

For running the bot not in a container, the best thing would probably be to look in the bots [Dockerfile](https://github.com/SpaceXLaunchBot/SpaceXLaunchBot/blob/master/Dockerfile) and you could then follow those steps normally which should set the bot up, althought probably not the "INSIDE_DOCKER" var or the docker health check stuff.

Keep in mind I've never tried a full deployment outside of Docker so on your own head be it if something messes up!

> whats the difference between spacexlaunchbot/ and spacexlaunchbot/spacexlaunchbot/ ?

spacexlaunchbot/ is the GitHub organisation that contains the 3 repos; spacexlaunchbot/spacexlaunchbot/ is the actual code for the bot, spacexlaunchbot/site is the code for the website (front and backend), and spacexlaunchbot/deploy is the deployment code for the whole thing.

Sorry I don't have a massive amount of time to help but if you have any more questions feel free to ask 😄

**Comment by rich1488** [comment]
you've been more than helpful, much appreciated.

but as far as the difference between spacexlaunchbot/ and spacexlaunchbot/spacexlaunchbot i'm referring to the same repo, just the different directories within this repo.

**Comment by psidex** [comment]
Oh I see, yeah so spacexlaunchbot/ (if you're talking about the root directory of the repo) contains everything required to run and maintain the bot, spacexlaunchbot/spacexlaunchbot contains just the Python code.

So in the root directory, for example, there's  `.github/workflows` and `setup.cfg` which are for running the GitHub action that lints and checks the code, `requirements.txt` and `setup.py` are for installing the bot as a Python package (which is what happens inside the Docker container), etc, but inside spacexlaunchbot/spacexlaunchbot you've got just `.py` files/
